import express from "express";
import mongoose from "mongoose";

import musicModel from "../models/musics.js";
import lyricsModel from "../models/lyrics.js";
import cleanTxt from "../utils/clearTitle.js";

import {
    getUnSyncedLyrics,
    setSyncedSong,
    getSongsToBeSynced
} from "../handlers/admin/lyricSync.js";
import {
    addLyricsToSong,
    addLyricsDirectToSong
} from "../handlers/admin/addLyric.js";
import getRemainingSongs from "../handlers/admin/getRemainingSong.js";
import addNewLyricToDb from "../handlers/admin/addNewLyricToDb.js";
import getSongById from "../handlers/admin/getSongById.js";
import { searchLyric, searchSong } from "../handlers/admin/search.js";
import removeLyric from "../handlers/admin/removeLyric.js";
import {
    updateArtist,
    deleteSong,
    swapLyric
} from "../handlers/admin/manageSong.js";
import cloudStatus from "../handlers/admin/cloudStatus.js";

const router = express.Router();

router.post("/getUnSyncedLyrics", getUnSyncedLyrics);

router.post("/setSyncedSong", setSyncedSong);

router.post("/removeLyric", removeLyric);

router.post("/addLyricsToSong", addLyricsToSong); // add lyrics from lyrics db

router.post("/addLyricsDirectToSong", addLyricsDirectToSong); // add lyrics that passed as array

router.post("/getRemainingSongsWithoutLyric", getRemainingSongs);

router.post("/getSongsToBeSynced", getSongsToBeSynced);

router.post("/getSongById", getSongById);

router.post("/searchSong", searchSong);

router.post("/searchLyric", searchLyric);

router.post("/deleteSong", deleteSong);

router.post("/updateArtist", updateArtist);

router.post("/swapLyric", swapLyric);

// lyrics model

router.post("/addNewLyricToDb", addNewLyricToDb);

// cloud

router.get("/cloudStatus", cloudStatus);

// youtube subtitles

router.post("/getRemainingSongsForAddSubtitleAsLyrics", async (req, res) => {
    try {
        const { limit, page } = req.body;

        const songs = await musicModel
            .find({
                // lang: "ml",
                $or: [
                    { lyrics: { $exists: false } },
                    { lyrics: null },
                    { lyrics: { $size: 0 } }
                ]
            })
            .sort({ createdAt: -1 })
            .skip((page - 1) * limit)
            .limit(limit);

        return res.json({ songs });
    } catch (e) {
        console.error(e);
    }
});

router.post("/addSubtitleToLyrics", async (req, res) => {
    const { lyrics, id } = req.body;

    await musicModel.findByIdAndUpdate(id, {
        $set: { lyrics, synced: true, isLyricsAutoGenerated: true }
    });

    res.json({ success: true });
});


router.post("/transferAsset", async (req, res) => {
    try {
        const { id, url, cover } = req.body;

        if (!id || !url) {
            return res.status(400).json({ success: false, message: "id, url, and cover are required" });
        }

        await musicModel.findByIdAndUpdate(id, {
            $set: { url, cover }
        });

        res.json({ success: true, message: "Asset transferred successfully" });
    } catch (error) {
        console.error("Error transferring asset:", error);
        res.status(500).json({ success: false, message: "Internal Server Error" });
    }
});


router.get("/findByCloudName", async (req, res) => {
    try {
        const cloudName = "dnlrvfgjk";

        // Regex pattern to match URLs containing the cloud name
        const regex = new RegExp(`res\\.cloudinary\\.com\\/${cloudName}\\/`, "i");

        // Find songs where either url or cover belongs to this cloud name
        const songs = await musicModel.find({
            $or: [
                { url: { $regex: regex } },
                { cover: { $regex: regex } }
            ]
        });

        if (!songs.length) {
            return res.status(404).json({ success: false, message: "No songs found for this Cloudinary account" });
        }

        res.json({ success: true, count: songs.length, songs });
    } catch (error) {
        console.error("Error finding songs by cloud name:", error);
        res.status(500).json({ success: false, message: "Internal Server Error" });
    }
});


export default router;

(async () => {
    let songs = await musicModel
        .find({
            $or: [
                { lyrics: { $exists: false } },
                { lyrics: null },
                { lyrics: { $size: 0 } }
            ]
        })

    console.log("remaining: ", songs.length);

})();
