import mongoose from "mongoose";

const musicSchema = mongoose.Schema({
    title: {
        type: String,
        required: true,
        index: true
    },
    url: {
        type: String,
        required: true
    },
    cover: String,
    duration: Number,
    artist: {
        type: String,
        default: "Unknown"
    },
    ytId: String,
    synced: {
        type: Boolean,
        default: false
    },
    lyrics: [
        {
            start: Number,
            end: Number,
            line: String
        }
    ],
    lang: String,
    isLyricsAutoGenerated: {
        type: Boolean,
        default: false
    },
    lyricsAsText: [{ type: String }],
    stableRandom: Number,

    ai: {
        processed: {
            type: Boolean,
            default: false,
            index: true
        },

        processing: {
            type: Boolean,
            default: false
        },

        // NEW: timestamp of when "processing" was last set to true.
        // Used to detect and recover songs that got stuck mid-run
        // (e.g. the script crashed or was killed) so they can be
        // safely re-claimed instead of staying locked forever.
        processingAt: {
            type: Date
        },

        webSearched: {
            type: Boolean,
            default: false
        },

        webSearchedAt: Date,

        webSources: [
            {
                title: String,
                url: String,
                snippet: String
            }
        ],

        processedAt: Date,

        language: String,

        moods: [String],
        themes: [String],
        genres: [String],
        situations: [String],

        energy: String,

        description: String,

        searchText: String,

        // select: false — embeddings are only needed for vector search/recommend
        // queries, never for normal song reads (list, player, search-by-title,
        // etc). Excluding them by default keeps ordinary queries cheap even
        // with 20k+ documents. Explicitly opt in with .select("+ai.embedding")
        // wherever you actually need it.
        embedding: {
            type: [Number],
            select: false
        },

        error: String
    },

    createdAt: {
        type: Date,
        default: Date.now
    }
});

musicSchema.index({ createdAt: -1 });

// Helps the atomic "claim next song" query (ai.processed=false, sorted by createdAt)
musicSchema.index({ "ai.processed": 1, "ai.processing": 1, createdAt: 1 });

musicSchema.index(
    {
        title: "text",
        artist: "text",
        lyricsAsText: "text"
    },
    {
        weights: {
            title: 10,
            artist: 5,
            lyricsAsText: 1
        },
        name: "music_text_search"
    }
);

export default mongoose.model("music", musicSchema);
