import mongoose from "mongoose";

const musicSchema = mongoose.Schema({
    title: {
        type: String,
        required: true,
        index: true
    },
    url: {
        type: String,
        required: true
    },
    cover: String,
    duration: Number,
    artist: {
        type: String,
        default: "Unknown"
    },
    ytId: String,
    synced: {
        type: Boolean,
        default: false
    },
    lyrics: [
        {
            start: Number,
            end: Number,
            line: String
        }
    ],
    lang: String,
    isFav: {
        type: Boolean,
        default: false
    },
    favAt: {
        type: Date,
        default: null
    },
    isLyricsAutoGenerated: {
        type: Boolean,
        default: false
    },
    lyricsAsText: [{ type: String }],
    stableRandom: Number,
    colors: {
        background: String,
        primary: String,
        secondary: String,
        detail: String,
        average: String,
        dominant: String,
        lightVibrant: String,
        vibrant: String,
        darkVibrant: String,
        lightMuted: String,
        muted: String,
        darkMuted: String,
    },

    createdAt: {
        type: Date,
        default: Date.now
    }
});

musicSchema.index({ createdAt: -1 });


musicSchema.index(
    {
        title: "text",
        artist: "text",
        lyricsAsText: "text"
    },
    {
        weights: {
            title: 10,
            artist: 5,
            lyricsAsText: 1
        },
        name: "music_text_search"
    }
);

export default mongoose.model("music", musicSchema);
