import mongoose from "mongoose";

const musicSchema = mongoose.Schema({
    title: {
        type: String,
        required: true,
        index: true
    },
    url: {
        type: String,
        required: true
    },
    cover: String,
    duration: Number,
    artist: {
        type: String,
        default: "Unknown"
    },
    ytId: String,
    synced: {
        type: Boolean,
        default: false
    },
    lyrics: [
        {
            start: Number,
            end: Number,
            line: String
        }
    ],
    lang: String,
    isLyricsAutoGenerated: {
        type: Boolean,
        default: false
    },
    lyricsAsText: [{ type: String }],
    stableRandom: Number,
    createdAt: {
        type: Date,
        default: Date.now
    }
});

musicSchema.index({ createdAt: -1 });

// Compound text index for full-text search across title, artist, and lyrics.
// Weights control how strongly each field influences MongoDB's textScore:
//   title       → highest (10) — primary search field
//   artist      → medium  (5)  — searching by artist name
//   lyricsAsText → lowest (1)  — fallback lyric search
// MongoDB only allows ONE text index per collection.
musicSchema.index(
    {
        title: "text",
        artist: "text",
        lyricsAsText: "text"
    },
    {
        weights: {
            title: 10,
            artist: 5,
            lyricsAsText: 1
        },
        name: "music_text_search"
    }
);

export default mongoose.model("music", musicSchema);
